- name: create users
  hosts: windows
  become: true
  vars_files:
    - users_list.yml
    - secrets.yml
  tasks:
    - name: create admin group
      group:
        name: Admin
        state: present

    - name: create Consulatant group
      group:
        name: "{{ item.job }}"
        state: present
      when: inventory_hostname in groups.prod and item.job == consulting
      loop: "{{ users }}"

    - name: create Technology group
      group:
        name: "{{ item.job }}"
        state: present
      when: inventory_hostname in groups.dev and item.job == Technology
      loop: "{{ users }}"
    - name: create users
      user:
        name: "{{ item.name }}"
        groups: "Admin, {{ item.job }}"
        append: true
        state: present
        password: "{{ pw_manager | password_hash ('sha512') }}"
        shell: /bin/bash
      when: inventory_hostname in groups.prod
      loop: "{{ users }}"

    - name: create users
      user:
        name: "{{ item.name }}"
        groups: "Admin, {{ item.job }}"
        append: true
        state: present
        password: "{{ pw_developer | password_hash ('sha512') }}"
        shell: /bin/bash
      when: inventory_hostname in groups.dev
      loop: "{{ users }}"
